### ISSUE TITLE
Can you provide example for how to run the standalone opencv library?

### ISSUE THREAD

**Issue by Pushkar2307** [robotics-upo/plane_detector#3]
Hi, I'm trying to run the standalone library with opencv but I'm confused on how to.
Can you give an example on how I should go about it?

**Comment by david-alejo** [comment]
Dear Pushkar,

I would try to include an example of the standalone operation.

Best regards,

**Comment by david-alejo** [comment]
Added a standalone example tested with TUM images. Please check it and I'll close it if it's OK.
